# Generated by Django 2.1.1 on 2019-04-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='trainingTask',
            fields=[
                ('oid', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('trainingName', models.CharField(max_length=200)),
                ('trainingDataFile', models.CharField(max_length=200)),
                ('typeOfModel', models.CharField(max_length=100)),
                ('onTraining', models.IntegerField(default=-1)),
                ('uploadTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
