# Generated by Django 2.1.1 on 2019-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainingTask',
            fields=[
                ('oid', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('trainingName', models.CharField(max_length=200)),
                ('trainingDataFile', models.CharField(max_length=200)),
                ('typeOfModel', models.CharField(max_length=100)),
                ('onTraining', models.IntegerField(default=-1)),
                ('uploadTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
