# Generated by Django 2.1.1 on 2019-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLWebService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
