# Generated by Django 2.1.1 on 2019-04-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLWebService', '0002_auto_20190410_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingtask',
            old_name='traingName',
            new_name='trainingName',
        ),
    ]
