# Generated by Django 2.1.1 on 2019-04-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLWebService', '0002_trainingtask_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mluser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
