# Generated by Django 2.1.1 on 2019-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLWebService', '0003_auto_20190410_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='oid',
            field=models.IntegerField(db_column='FId', primary_key=True, serialize=False),
        ),
    ]
