# Generated by Django 2.1.1 on 2019-04-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLWebService', '0004_auto_20190410_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainingModels',
        ),
    ]
