# Generated by Django 2.1.1 on 2019-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLWebService', '0005_delete_trainingmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='uploadTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
